import { Invoice } from "@/lib/definitions";

const invoices: Invoice[] = [
    {
        customer_id: "1",
        order_name: "Order 1",
        description: "Description 1",
        amount: 132,
        status: "Pending",
        date: "2021-01-01",
    },
    {
        customer_id: "2",
        order_name: "Order 2",
        description: "Description 2",
        amount: 368,
        status: "Paid",
        date: "2021-01-02",
    },
    {
        customer_id: "3",
        order_name: "Order 3",
        description: "Description 3",
        amount: 345,
        status: "Shipped",
        date: "2021-01-03",
    },
    {
        customer_id: "4",
        order_name: "Order 4",
        description: "Description 4",
        amount: 789,
        status: "Delivered",
        date: "2021-01-04",
    },
    {
        customer_id: "5",
        order_name: "Order 5",
        description: "Description 5",
        amount: 567,
        status: "Pending",
        date: "2021-01-05",
    },
    { 
        customer_id: "6",
        order_name: "Order 6",
        description: "Description 6",
        amount: 34563,
        status: "Paid",
        date: "2021-01-06",
    },
    {
        customer_id: "7",
        order_name: "Order 7",
        description: "Description 7",
        amount: 234,
        status: "Paid",
        date: "2021-01-07",
    },
    {
        customer_id: "8",
        order_name: "Order 8",
        description: "Description 8",
        amount: 3762,
        status: "Shipped",
        date: "2021-01-08",
    },
    {
        customer_id: "9",
        order_name: "Order 9",
        description: "Description 9",
        amount: 1234,
        status: "Delivered",
        date: "2021-01-09",
    },
    {
        customer_id: "10",
        order_name: "Order 10",
        description: "Description 10",
        amount: 6789,
        status: "Pending",
        date: "2021-01-10",
    },
    {
        customer_id: "11",
        order_name: "Order 11",
        description: "Description 11",
        amount: 456,
        status: "Paid",
        date: "2022-04-13",
    },
    {
        customer_id: "12",
        order_name: "Order 12",
        description: "Description 12",
        amount: 234,
        status: "Shipped",
        date: "2022-04-14",
    },
    {
        customer_id: "13",
        order_name: "Order 13",
        description: "Description 13",
        amount: 3456,
        status: "Delivered",
        date: "2022-04-15",
    },
    {
        customer_id: "14",
        order_name: "Order 14",
        description: "Description 14",
        amount: 6780,
        status: "Pending",
        date: "2022-04-16",
    },
    {
        customer_id: "15",
        order_name: "Order 15",
        description: "Description 15",
        amount: 1230,
        status: "Paid",
        date: "2022-04-17",
    },
    {
        customer_id: "16",
        order_name: "Order 16",
        description: "Description 16",
        amount: 4560,
        status: "Paid",
        date: "2022-04-18",
    },
    {
        customer_id: "17",
        order_name: "Order 17",
        description: "Description 17",
        amount: 7890,
        status: "Shipped",
        date: "2022-04-19",
    },
    {
        customer_id: "18",
        order_name: "Order 18",
        description: "Description 18",
        amount: 2342,
        status: "Delivered",
        date: "2022-04-20",
    },
    {
        customer_id: "19",
        order_name: "Order 19",
        description: "Description 19",
        amount: 5674,
        status: "Pending",
        date: "2022-04-21",
    },
    {
        customer_id: "20",
        order_name: "Order 20",
        description: "Description 20",
        amount: 345,
        status: "Paid",
        date: "2022-04-22",
    },
];